version: '3.8'

services:
  app:
    build: .
    container_name: ci4_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - appnet

  db:
    image: mysql:5.7
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: surat1
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
