version: '3.8'

services:
  app:
    build: .
    container_name: ci4_app
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    networks:
      - appnet

  db:
    image: mysql:5.7
    container_name: ci4_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: surat1
    ports:
      - "3306:3306"
    networks:
      - appnet


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: ci4_db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin123
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
